server:
  port: 9528

spring:
  banner:
    location: classpath:banner.txt
  application:
    name: general-gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 43.138.29.202:38848

    gateway:
      routes:
        - id: general-user
          uri: lb://general-user-service
          predicates:
            - Path=/api/user_service/user/**, /api/user_service/role/**, /api/user_service/organization/**
            - Method=GET, POST
            - Header=Accept
            - Weight=group1, 100