server:
  port: 9527

spring:
  banner:
    location: classpath:banner.txt
  application:
    name: general-gateway-service
  cloud:
    nacos:
      discovery:
        namespace: general
        group: GENERAL_GROUP
      config:
        namespace: general
        group: GENERAL_GROUP
        import-check:
          enabled: false
      server-addr: "[2408:400a:738:5300:e6c1:1542:b082:d743]:38848"
      username: nacos
      password: Password@13
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
      web-context-unify: false
      datasource:
        ds1:
          nacos:
            server-addr: "[2408:400a:738:5300:e6c1:1542:b082:d743]:38848"
            username: nacos
            password: Password@13
            data-id: ${spring.application.name}
            group-id: GENERAL_GROUP
            namespace: general
            data-type: json
            rule-type: flow
    gateway:
      routes:
        - id: general-auth
          uri: lb://general-auth
          predicates:
            - Path=/api/auth-service/**
            - Method=GET, POST, PUT, DELETE
        - id: general-log
          uri: lb://general-log
          predicates:
            - Path=/api/log_service/**
            - Method=GET, POST, PUT, DELETE
  data:
    redis:
      host: 2408:400a:738:5300:e6c1:1542:b082:d743
      port: 36379
      password: Password@13
      database: 7
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: Authorization
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: simple-uuid
  # 是否输出操作日志
  is-log: true
  # token 前缀
  token-prefix: Bearer
seata:
  enabled: false