server:
  port: 8020
spring:
  application:
    name: general-base
  cloud:
    nacos:
      discovery:
        namespace: general
        group: GENERAL_GROUP
      config:
        namespace: general
        group: GENERAL_GROUP
        import-check:
          enabled: false
      server-addr: "[2408:400a:738:5300:e6c1:1542:b082:d743]:38848"
      username: nacos
      password: Password@13
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
      web-context-unify: false
      datasource:
        ds1:
          nacos:
            server-addr: "[2408:400a:738:5300:e6c1:1542:b082:d743]:38848"
            username: nacos
            password: Password@13
            data-id: ${spring.application.name}
            group-id: GENERAL_GROUP
            namespace: general
            data-type: json
            rule-type: flow
  data:
    redis:
      host: 2408:400a:738:5300:e6c1:1542:b082:d743
      port: 36379
      password: Mr8!pj_qk8rizLC
      database: 7
seata:
  enabled: false