server:
  port: 8021

spring:
  banner:
    location: classpath:banner.txt
  application:
    name: general-auth
  cloud:
    nacos:
      discovery:
        server-addr: 43.138.29.202:38848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
      web-context-unify: false
      datasource:
        ds1:
          nacos:
            server-addr: 43.138.29.202:38848
            data-id: ${spring.application.name}
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: flow
  data:
    redis:
      host: 43.138.29.202
      port: 36379
      password: Mr8!pj_qk8rizLC
      database: 7

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: saToken
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: simple-uuid
  # 是否输出操作日志
  is-log: true
