server:
  port: 18000

spring:
  banner:
    location: classpath:banner.txt
  mvc:
    problemdetails:
      enabled: true
  profiles:
    active: default
  data:
    redis:
      jedis:
        pool:
          enabled: true
          min-idle: 1
          max-active: 8
      database: 15
      host: 43.138.29.202
      port: 36379
      password: Mr8!pj_qk8rizLC
      client-type: jedis
  datasource:
    url: jdbc:p6spy:mysql://43.138.29.202:33306/general?serverTimezone=Asia/Shanghai&characterEncoding=utf8
    driverClassName: com.p6spy.engine.spy.P6SpyDriver
    username: root
    password: Mr8!pj_qk8rizLC
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
        allow: "*"
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 100
          db-type: mysql
        wall:
          db-type: mysql
          config:
            delete-allow: false
            drop-table-allow: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss.SSS
  kafka:
    bootstrap-servers: 43.138.29.202:39092


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/*.xml
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  type-aliases-package: org.john.*.domain

logging:
  charset:
    console: UTF-8
    file: UTF-8
management:
  endpoints:
    web:
      exposure:
        exclude: "*"
springfox:
  documentation:
    swagger:
      v2:
        enabled: true